<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>OneClickClose</RootNamespace>
    <AssemblyName>OneClickClose</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <NoWarn>WFO1000</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OneClickClose.Core\OneClickClose.Core.csproj" />
  </ItemGroup>

</Project>
